
mocap_model: 'SKELETON_WITHOUT_TOES'

rigid_bodies:
    '1':
        pose: mocap_node/pose
        pose2d: mocap_node/ground_pose
        tf: mocap_node/tf
    '2':
        pose: mocap_node/pose2
        pose2d: mocap_node/ground_pose2
