
mocap_model: 'SKELETON_WITHOUT_TOES'
publish_transform: No
publish_pose: No
publish_ground_pose: No

rigid_bodies:
    '1':
        pose: mocap_node/pose
        pose2d: mocap_node/ground_pose
        tf: mocap_node/tf
    '2':
        pose: mocap_node/pose2
        pose2d: mocap_node/ground_pose2
